# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.zone.com.ng:
  peer0.uba.zone.com.ng:
  peer1.uba.zone.com.ng:


networks:
  byfn:

services:

  orderer0.zone.com.ng:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.zone.com.ng
    container_name: orderer0.zone.com.ng
    environment:
            - ORDERER_HOST=orderer0.zone.com.ng
            - CONFIGTX_ORDERER_ORDERERTYPE=kafka
            - CONFIGTX_ORDERER_KAFKA_BROKERS=[35.231.18.99:9092,35.190.146.148:9092,35.231.124.102:9092]
            - ORDERER_KAFKA_RETRY_SHORTINTERVAL=1s
            - ORDERER_KAFKA_RETRY_SHORTTOTAL=30s
            - ORDERER_KAFKA_VERBOSE=true
            - ORDERER_GENERAL_GENESISPROFILE=SampleInsecureKafka
            - ORDERER_ABSOLUTEMAXBYTES=${ORDERER_ABSOLUTEMAXBYTES}
            - ORDERER_PREFERREDMAXBYTES=${ORDERER_PREFERREDMAXBYTES}
    volumes:
            - ../crypto-config/ordererOrganizations/zone.com.ng/orderers/orderer0.zone.com.ng/msp:/var/hyperledger/msp
            - ../crypto-config/ordererOrganizations/zone.com.ng/orderers/orderer0.zone.com.ng/tls:/var/hyperledger/tls
            - ../config/:/var/hyperledger/configs

    networks:
      - byfn
      
  orderer1.zone.com.ng:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.zone.com.ng
    container_name: orderer1.zone.com.ng
    environment:
            - ORDERER_HOST=orderer0.zone.com.ng
            - CONFIGTX_ORDERER_ORDERERTYPE=kafka
            - CONFIGTX_ORDERER_KAFKA_BROKERS=[35.231.18.99:9092,35.190.146.148:9092,35.231.124.102:9092]
            - ORDERER_KAFKA_RETRY_SHORTINTERVAL=1s
            - ORDERER_KAFKA_RETRY_SHORTTOTAL=30s
            - ORDERER_KAFKA_VERBOSE=true
            - ORDERER_GENERAL_GENESISPROFILE=SampleInsecureKafka
            - ORDERER_ABSOLUTEMAXBYTES=${ORDERER_ABSOLUTEMAXBYTES}
            - ORDERER_PREFERREDMAXBYTES=${ORDERER_PREFERREDMAXBYTES}
    volumes:
            - ../crypto-config/ordererOrganizations/zone.com.ng/orderers/orderer0.zone.com.ng/msp:/var/hyperledger/msp
            - ../crypto-config/ordererOrganizations/zone.com.ng/orderers/orderer0.zone.com.ng/tls:/var/hyperledger/tls
            - ../config/:/var/hyperledger/configs

    networks:
      - byfn

  peer0.uba.zone.com.ng:
    container_name: peer0.uba.zone.com.ng
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.uba.zone.com.ng
    networks:
      - byfn

  peer1.uba.zone.com.ng:
    container_name: peer1.uba.zone.com.ng
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.uba.zone.com.ng
    networks:
      - byfn

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=INFO
      #- CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.uba.zone.com.ng:7051
      - CORE_PEER_LOCALMSPID=UbaMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/uba.zone.com.ng/peers/peer0.uba.zone.com.ng/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/uba.zone.com.ng/peers/peer0.uba.zone.com.ng/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/uba.zone.com.ng/peers/peer0.uba.zone.com.ng/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/uba.zone.com.ng/users/Admin@uba.zone.com.ng/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.zone.com.ng
      - peer0.uba.zone.com.ng
      - peer1.uba.zone.com.ng
    networks:
      - byfn
