# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  peer0.fcmb.zone.com.ng:
  peer1.fcmb.zone.com.ng:

networks:
  byfn:

services:

  peer0.fcmb.zone.com.ng:
    container_name: peer0.fcmb.zone.com.ng
    extends:
      file: base/peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.fcmb.zone.com.ng
      - CORE_PEER_ADDRESS=peer0.fcmb.zone.com.ng:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.fcmb.zone.com.ng:7051
      - CORE_PEER_LOCALMSPID=fcmbMSP
    volumes:
        - /var/run/:/host/var/run/
        - ./org3-artifacts/crypto-config/peerOrganizations/fcmb.zone.com.ng/peers/peer0.fcmb.zone.com.ng/msp:/etc/hyperledger/fabric/msp
        - ./org3-artifacts/crypto-config/peerOrganizations/fcmb.zone.com.ng/peers/peer0.fcmb.zone.com.ng/tls:/etc/hyperledger/fabric/tls
        - peer0.fcmb.zone.com.ng:/var/hyperledger/production
    ports:
      - 11051:7051
      - 11053:7053
    networks:
      - byfn

  peer1.fcmb.zone.com.ng:
    container_name: peer1.fcmb.zone.com.ng
    extends:
      file: base/peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.fcmb.zone.com.ng
      - CORE_PEER_ADDRESS=peer1.fcmb.zone.com.ng:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.fcmb.zone.com.ng:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.fcmb.zone.com.ng:7051
      - CORE_PEER_LOCALMSPID=fcmbMSP
    volumes:
        - /var/run/:/host/var/run/
        - ./org3-artifacts/crypto-config/peerOrganizations/fcmb.zone.com.ng/peers/peer1.fcmb.zone.com.ng/msp:/etc/hyperledger/fabric/msp
        - ./org3-artifacts/crypto-config/peerOrganizations/fcmb.zone.com.ng/peers/peer1.fcmb.zone.com.ng/tls:/etc/hyperledger/fabric/tls
        - peer1.fcmb.zone.com.ng:/var/hyperledger/production
    ports:
      - 12051:7051
      - 12053:7053
    networks:
      - byfn


  fcmbcli:
    container_name: fcmbcli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=INFO
      #- CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=fcmbcli
      - CORE_PEER_ADDRESS=peer0.fcmb.zone.com.ng:7051
      - CORE_PEER_LOCALMSPID=fcmbMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/fcmb.zone.com.ng/peers/peer0.fcmb.zone.com.ng/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/fcmb.zone.com.ng/peers/peer0.fcmb.zone.com.ng/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/fcmb.zone.com.ng/peers/peer0.fcmb.zone.com.ng/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/fcmb.zone.com.ng/users/Admin@fcmb.zone.com.ng/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/chaincode
        - ./org3-artifacts/crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./crypto-config/peerOrganizations/org1.example.com:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com
        - ./crypto-config/peerOrganizations/org2.example.com:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org2.example.com
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
    depends_on:
      - peer0.fcmb.zone.com.ng
      - peer1.fcmb.zone.com.ng
    networks:
      - byfn
