# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer.zone.com.ng:
    container_name: orderer.zone.com.ng
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    environment:
      - ORDERER_GENERAL_LOGLEVEL=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${CORE_PEER_NETWORKID}_behave
      - ORDERER_HOME=/var/hyperledger/orderer            
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_LEDGERTYPE=ram      
      - CONFIGTX_ORDERER_ORDERERTYPE=kafka
      - CONFIGTX_ORDERER_BATCHSIZE_MAXMESSAGECOUNT=${CONFIGTX_ORDERER_BATCHSIZE_MAXMESSAGECOUNT}
      - CONFIGTX_ORDERER_BATCHTIMEOUT=${CONFIGTX_ORDERER_BATCHTIMEOUT}
      - CONFIGTX_ORDERER_ADDRESSES=[127.0.0.1:7050]
           # enabled TLS      
      - ORDERER_TLS_CLIENTAUTHREQUIRED=${ORDERER_TLS_CLIENTAUTHREQUIRED}
      - ORDERER_TLS_CLIENTROOTCAS_FILES=/var/hyperledger/users/Admin@example.com/tls/ca.crt
      - ORDERER_TLS_CLIENTCERT_FILE=/var/hyperledger/users/Admin@example.com/tls/client.crt
      - ORDERER_TLS_CLIENTKEY_FILE=/var/hyperledger/users/Admin@example.com/tls/client.key      
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ../crypto-config/ordererOrganizations/zone.com.ng/orderers/orderer.zone.com.ng/msp:/var/hyperledger/orderer/msp
    - ../crypto-config/ordererOrganizations/zone.com.ng/orderers/orderer.zone.com.ng/tls/:/var/hyperledger/orderer/tls
    - orderer.zone.com.ng:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.uba.zone.com.ng:
    container_name: peer0.uba.zone.com.ng
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.uba.zone.com.ng
      - CORE_PEER_ADDRESS=peer0.uba.zone.com.ng:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.uba.zone.com.ng:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.uba.zone.com.ng:7051
      - CORE_PEER_LOCALMSPID=UbaMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/uba.zone.com.ng/peers/peer0.uba.zone.com.ng/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/uba.zone.com.ng/peers/peer0.uba.zone.com.ng/tls:/etc/hyperledger/fabric/tls
        - peer0.uba.zone.com.ng:/var/hyperledger/production
    ports:
      - 7051:7051
      - 7053:7053

  peer1.uba.zone.com.ng:
    container_name: peer1.uba.zone.com.ng
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.uba.zone.com.ng
      - CORE_PEER_ADDRESS=peer1.uba.zone.com.ng:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.uba.zone.com.ng:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.uba.zone.com.ng:7051
      - CORE_PEER_LOCALMSPID=UbaMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/uba.zone.com.ng/peers/peer1.uba.zone.com.ng/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/uba.zone.com.ng/peers/peer1.uba.zone.com.ng/tls:/etc/hyperledger/fabric/tls
        - peer1.uba.zone.com.ng:/var/hyperledger/production

    ports:
      - 8051:7051
      - 8053:7053